buildscript {
    ext.kotlin_version = '1.8.22'
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'io.github.http-builder-ng:http-builder-ng-core:1.0.3'
        classpath 'com.android.tools.build:gradle:8.1.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

plugins {
    id 'com.diffplug.spotless' version '6.12.1'
}

allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
}

apply from: "$project.rootDir/spotless.gradle"
