buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath(libs.github.http.builder.core)
        classpath(libs.android.tools.build.gradle)
        classpath(libs.kotlin.gradle)
    }
}

plugins {
    alias(libs.plugins.spotless)
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.maven.central.publish)
}

allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
}

apply from: "$project.rootDir/spotless.gradle"
