apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    compileSdk = 36

    defaultConfig {
        minSdkVersion = 23
        targetSdkVersion = 34
        buildConfigField("long", "VERSION_CODE", VERSION_CODE)
        buildConfigField("String","VERSION_NAME","\"${VERSION_NAME}\"")
    }

    buildTypes {
        debug {
            debuggable = true
            minifyEnabled = false
        }
        release {
            debuggable = false
            minifyEnabled = false
            consumerProguardFiles = ['proguard-rules.pro']
        }
    }

    buildFeatures {
        buildConfig = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
    kotlin {
        jvmToolchain(17)
    }

    namespace = 'com.raygun.raygun4android'

}

afterEvaluate {
    android.libraryVariants.all { variant ->
        def variantName = variant.name
        def capitalizedName = variantName.capitalize()

        tasks.named("bundle${capitalizedName}Aar").configure {
            archiveFileName.set(variantName == 'debug' ? "raygun4android-debug.aar" : "raygun4android.aar")
        }
    }
}

android.libraryVariants.all { variant ->
    if (variant.name == 'release') {
        tasks.register("androidJavadocs", Javadoc) {
            source = android.sourceSets.main.java.srcDirs
            source += android.sourceSets.release.java.srcDirs
            classpath += project.files(android.getBootClasspath().join(File.pathSeparator))
            classpath += variant.javaCompileProvider.get().classpath
            classpath += files("build/generated/source/buildConfig/release")

            options.windowTitle = "Raygun4Android"
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation(libs.androidx.core)
    implementation(libs.androidx.appcompat)
    implementation(libs.gson)
    implementation(libs.okhttp)
    implementation(libs.timber)
    implementation(libs.androidx.work.runtime)

    testImplementation(libs.junit)
    testImplementation(libs.mockito.core)
    testImplementation(libs.mockito.inline)
    testImplementation(libs.mockito.kotlin)
}

// Commented code to push to lib repos as that code will need to change
 apply from: 'maven-central-publish.gradle'
