plugins {
    alias(libs.plugins.android.library)
}

android {
    compileSdk = 36

    defaultConfig {
        minSdk = 23
        targetSdk = 34
        buildConfigField("long", "VERSION_CODE", VERSION_CODE)
        buildConfigField("String","VERSION_NAME","\"${VERSION_NAME}\"")
    }

    buildTypes {
        debug {
            debuggable = true
            minifyEnabled = false
        }
        release {
            debuggable = false
            minifyEnabled = false
            consumerProguardFiles = ['proguard-rules.pro']
        }
    }

    buildFeatures {
        buildConfig = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    namespace = 'com.raygun.raygun4android'

}

afterEvaluate {
    tasks.named("bundleDebugAar").configure {
        archiveFileName.set("raygun4android-debug.aar")
    }
    tasks.named("bundleReleaseAar").configure {
        archiveFileName.set("raygun4android.aar")
    }
}

dependencies {
    implementation(libs.androidx.core)
    implementation(libs.androidx.appcompat)
    implementation(libs.gson)
    implementation(libs.okhttp)
    implementation(libs.timber)
    implementation(libs.androidx.work.runtime)

    testImplementation(libs.junit)
    testImplementation(libs.mockito.core)
    testImplementation(libs.mockito.inline)
    testImplementation(libs.mockito.kotlin)
}

// Commented code to push to lib repos as that code will need to change
 apply from: 'maven-central-publish.gradle'
