apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    compileSdk 34

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 34
        buildConfigField("long", "VERSION_CODE", VERSION_CODE)
        buildConfigField("String","VERSION_NAME","\"${VERSION_NAME}\"")
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
        }
        release {
            debuggable false
            minifyEnabled false
            consumerProguardFiles 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
    kotlin {
        jvmToolchain(17)
    }

    namespace 'com.raygun.raygun4android'

    libraryVariants.all { variant ->
        variant.outputs.all { output ->
            if (outputFile != null && outputFileName.endsWith('.aar')) {
                if (variant.name == 'debug') {
                    outputFileName = "raygun4android-debug.aar"
                } else {
                    outputFileName = "raygun4android.aar"
                }
            }
        }
    }

    libraryVariants.all { variant ->
        if (variant.name == 'release') {
            task androidJavadocs(type: Javadoc) {
                source = android.sourceSets.main.java.srcDirs
                source += android.sourceSets.release.java.srcDirs
                classpath += project.files(android.getBootClasspath().join(File.pathSeparator))
                classpath += variant.javaCompiler.classpath
                classpath += files("build/generated/source/buildConfig/release")

                options.windowTitle = "Raygun4Android"
            }
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation(libs.androidx.core.core)
    implementation(libs.androidx.appcompat.appcompat)
    implementation(libs.gson)
    implementation(libs.okhttp)
    implementation(libs.timber)

    testImplementation(libs.junit)
    testImplementation(libs.mockito.core)
    testImplementation(libs.mockito.mockito.inline)
    testImplementation(libs.mockito.kotlin.mockito.kotlin)
}

// Commented code to push to lib repos as that code will need to change
// apply from: 'gradle-mvn-push.gradle'
